---
title: "Covid-19 Bundesländer"
author: "Jens Laufer"
date: "24 3 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message=F, echo = F)
```

```{r}
library(tidyverse)
library(glue)
source("dataGather.R")
source("dataPreprocess.R")
source("visualisations.R")
```

```{r}
data <- load.german.county.cases()
data <- data %>% preprocess.data()
```


```{r fig.height=10, fig.width=20}
data %>% filter(type=="historical") %>% cases.timelime()
```

```{r fig.height=10, fig.width=20}
data %>%
  filter(name == "Bayern" |
           name == "Baden-Württemberg" | name == "Nordrhein-Westfalen") %>%
  filter(type == "historical") %>%
  cases.timelime()
```
```{r fig.height=10, fig.width=20}
data %>%
  filter(name == "Bayern" |
           name == "Hessen" | 
           name == "Baden-Württemberg" | 
           name == "Nordrhein-Westfalen") %>%
  filter(type == "historical") %>%
  cases.timelime(.trans = "identity")
```
```{r fig.height=10, fig.width=20}

data %>%
  filter(
           name == "Bremen" |
           name == "Berlin" | 
           name == "Hamburg" ) %>% 
  filter(type == "historical") %>%
  cases.timelime(.trans = "identity")
```

