---
title: "Untitled"
author: "Jens Laufer"
date: "5 3 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(bbplot)
library(ggthemes)
library(scales)
library(glue)
library(tsbox)
library(forecast)

source("dataGather.R")
windowsFonts("Arial" = windowsFont("Arial"))
```


```{r}


.add.forecast <- function(data, .name, .h = 14) {
  data %>%
    filter(name == .name) %>%
    select(cases) %>%
    auto.arima() %>%
    forecast(h = .h) %>%
    as_tibble() %>%
    mutate(name = .name,
           day = row_number(),
           type = "forecast") %>%
    rename(cases = `Point Forecast`) %>%
    select(name, `cases`, type)
}

cases.timelime.country <- function(data, country) {
  data %>%
    filter(name == country & diff != 1) %>%
    #filter(cases > 0) %>%
    ggplot(aes(x = day, y = cases)) +
    geom_line(aes(linetype = type), size = 2.5, color = "steelblue") +
    scale_color_tableau() +
    #scale_y_log10(label = comma) +
    scale_x_continuous(breaks = seq(min(data$day), max(data$day), 2)) +
    labs(title = "Confirmed COVID-19 Cases in {country}" %>% glue(), subtitle =
           "Cases on logarithmic scale on a certain day of outbreak") +
    bbc_style()
}


cases.timelime <- function(data) {
  plot <- data %>%
    filter(cases > 0 & diff != 1) %>%
    ggplot(aes(x = day, y = cases, color = name)) +
    geom_line(aes(linetype = type), size = 2) +
    geom_hline(yintercept = 100) +
    geom_vline(xintercept = 0) +
    scale_color_tableau(palette = "Tableau 20") +
    scale_y_log10(label = comma) +
    scale_linetype_manual(values = c("dotted", "solid")) +
    scale_x_continuous(breaks = c(0, seq(min(data$day), max(data$day)), 10)) +
    labs(title = "Confirmed COVID-19 Cases", subtitle = "Cases on logarithmic scale in selected countries on a certain day of outbreak. Days are centered on the first past 100 cases.") +
    bbc_style()
  
  ggsave(plot,
         filename = "c:\\temp\\plot1.png",
         width = 20,
         height = 10)
  
  plot
  
}
```



```{r}
data1 <- load.data.bno.news()  %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(country, date) %>%
  arrange(desc(country, date)) %>%
  slice(n()) %>%
  rename(name = `country`) %>%
  ungroup() %>%
  mutate(type = "historical") %>% 
  ungroup()

data2 <- get.data.jhu()
```

```{r}

data1 <-  data1 %>%
  bind_rows(data1 %>% distinct(name)
            %>%
              pull(name) %>%
              map( ~ .add.forecast(data1, (.)))) %>%
  group_by(name) %>%
  mutate(day = row_number()) %>%

thresholds <- data1 %>% 
  group_by(name) %>% 
  filter(cases >= 100) %>% 
  slice(1) %>% 
  select(name, day) %>% 
  rename(threshold = day) %>% 
  ungroup()

data1 <- data1 %>% 
  inner_join(thresholds)%>% 
  mutate(day=day-threshold) %>% 
  select(-threshold) %>% 
  ungroup()
```





```{r}
filtered <- data1 %>%
  filter(
    name == "Germany" |
      name == "South Korea" |
      name == "France" |
      name == "Italy" |
      name == "United States" |
      name == "Iran" |
      name == "United Kingdom" |
      name == "Spain" |
      name == "Japan" |
      name == "Netherlands" |
      name == "Sweden" |
      name == "Switzerland"
  )

```


```{r}
china.filtered <- data2 %>%
  filter(`Country/Region` == "Mainland China") %>%
  select(date, `Country/Region`, confirmed) %>%
  group_by(date, `Country/Region`) %>% 
  summarise(confirmed=sum(confirmed)) %>% 
  ungroup() %>% 
  mutate(day=row_number(),  type = "historical") %>% 
  rename(name = `Country/Region`, cases = `confirmed`) %>% 
  ungroup() 

filtered <- filtered %>% bind_rows(china.filtered)
filtered <- filtered %>% 
  group_by(name) %>% 
  mutate(diff=cases/lag(cases)) %>% 
  ungroup()



```







```{r fig.height=15, fig.width=30}
filtered %>% 
  cases.timelime()
```





```{r fig.height=15, fig.width=30}
filtered %>% 
  filter(
      name == "Germany" |
      name == "Spain" |
      name == "Italy" |
      name == "Netherlands" |
      name == "Switzerland" |
      name == "France" 
  ) %>% 
  cases.timelime()
```

```{r fig.height=15, fig.width=30}
filtered %>% 
  filter(
      name == "South Korea" |
      name == "Iran" |
      name == "Italy"  
  ) %>% 
  cases.timelime() 
```


