---
title: "Untitled"
author: "Jens Laufer"
date: "5 3 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(bbplot)
library(ggthemes)
library(ggrepel)
library(scales)
library(glue)
library(tsbox)
library(forecast)

source("dataGather.R")
```


```{r}
.add.forecast <- function(data, .name, .h = 5) {
  data %>%
    filter(name == .name) %>%
    select(cases) %>%
    auto.arima() %>%
    forecast(h = .h) %>%
    as_tibble() %>%
    mutate(name = .name,
           day = row_number(),
           type = "forecast") %>%
    rename(cases = `Point Forecast`) %>%
    select(name, `cases`, type)
}

cases.timelime.country <- function(data, country) {
  data %>%
    filter(name == country & diff != 1) %>%
    #filter(cases > 0) %>%
    ggplot(aes(x = day, y = cases)) +
    geom_line(aes(linetype = type), size = 2.5, color = "steelblue") +
    scale_color_tableau() +
    #scale_y_log10(label = comma) +
    scale_x_continuous(breaks = seq(min(data$day), max(data$day), 2)) +
    labs(title = "Confirmed COVID-19 Cases in {country}" %>% glue(), subtitle =
           "Cases on logarithmic scale on a certain day of outbreak") +
    bbc_style()
}


cases.timelime <- function(data) {
  plot <- data %>%
    filter(cases > 0 & diff != 1) %>%
    ggplot(aes(x = day, y = cases, color = name)) +
    geom_line(aes(linetype = type), size = 2) +
    geom_hline(yintercept = 100) +
    geom_vline(xintercept = 0) +
    scale_color_tableau(palette = "Tableau 20") +
    scale_y_log10(label = comma) +
    scale_linetype_manual(values = c("solid", "dotted"), limits=c("historical", "forecast")) +
    scale_x_continuous(breaks = seq(min(data$day), max(data$day), 1)) +
    labs(title = "Confirmed COVID-19 Cases", subtitle = "Cases on logarithmic scale on a certain day of outbreak. Days are centered on the first past after 100 cases.") +
    bbc_style()
  
  plot
  
}

german <- function(plot){
  plot +
    labs(title = "Bestätigte COVID-19 Fälle", subtitle = "Fallzahlen auf logarithmischer Skala an einem bestimmten Tag nach Erreichen von 100 Fällen") 
}
```

```{r}


hospital.beds <- read_csv("data/hospital_beds.csv") %>% 
  select(-`Series Name`, -`Series Code`, -`Country Code`) %>% 
  gather(-`Country Name`, key = "year", value = "beds.per.1k.inhabitants") %>% 
  mutate(beds.per.1M.inhabitants=as.numeric(beds.per.1k.inhabitants)*1000) %>% 
  mutate(year=substring(year, 1, 4), year=as.numeric(year), year=as.factor(year)) %>% 
  rename(name=`Country Name`) %>% 
  group_by(name) %>% 
  na.omit() %>% 
  slice(n()) %>% 
  ungroup() %>% 
  select(-beds.per.1k.inhabitants)

 population <- read_csv("data/population.csv") %>% 
   mutate(Value=Value/1000000) %>% 
   rename(name=`Country Name`, population.mio=Value) %>% 
   group_by(name) %>% 
   arrange(Year) %>% 
   slice(n()) %>% 
   ungroup() %>% 
   select(name, population.mio)
```



```{r}
data <- load.data.bno.news()  %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(country, date) %>%
  arrange(desc(country, date)) %>%
  slice(n()) %>%
  rename(name = `country`) %>%
  ungroup() %>%
  mutate(type = "historical") %>%
  ungroup() %>% 
  filter()

```






```{r eval=F}

data.jhu <- get.data.jhu()
china.filtered <- data.jhu %>%
  filter(`Country/Region` == "China") %>%
  select(date, `Country/Region`, confirmed) %>%
  group_by(date, `Country/Region`) %>%
  summarise(confirmed = sum(confirmed)) %>%
  ungroup() %>%
  mutate(day = row_number(),  type = "historical") %>%
  rename(name = `Country/Region`, cases = `confirmed`) %>%
  ungroup()

data <- data %>% bind_rows(china.filtered)

rm(china.filtered)
rm(data.jhu)

```



```{r}

data <-  data %>%
  group_by(name) %>% 
  filter(!(datetime == max(datetime) & cases / lag(cases) == 1) ) %>% 
  ungroup() %>% 
  bind_rows(data %>% distinct(name)
            %>%
              pull(name) %>%
              map(~ .add.forecast(data, (.), 7))) %>%
  group_by(name) %>%
  mutate(day = row_number())

thresholds <- data %>%
  group_by(name) %>%
  filter(cases >= 100) %>%
  slice(1) %>%
  select(name, day) %>%
  rename(threshold = day) %>%
  ungroup()

data <- data %>%
  inner_join(thresholds) %>%
  mutate(day = day - threshold) %>%
  select(-threshold) %>%
  ungroup()


data <- data %>%
  group_by(name) %>%
  mutate(diff = cases / lag(cases)) %>%
  ungroup()
```

```{r}
data %>% filter(name=="Italy" & type=="historical") %>% 
  select(name, date, cases, day, diff) %>% 
  tail(10) %>% 
  ggplot(aes(x=date, y=diff))+
  geom_bar(stat="identity") +
  geom_smooth(
      
  )
  
```








```{r fig.height=15, fig.width=30}
data %>%
  filter(
    name == "Germany" |
      name == "South Korea" |
      name == "France" |
      name == "China" |
      name == "Italy" |
      name == "United States" |
      name == "Iran" |
      name == "United Kingdom" |
      name == "Spain" |
      name == "Japan" |
      name == "Canada" |
      name == "Netherlands" |
      name == "Sweden" |
      name == "Switzerland"
  ) %>%
  cases.timelime()
```





```{r fig.height=15, fig.width=30}
data %>% 
  filter(
      name == "Germany" |
      name == "Spain" |
      name == "Italy" |
      name == "France" 
  ) %>% 
  filter(type=="historical") %>% 
  cases.timelime()
```

```{r}
data %>% 
  filter(day==15) %>%  
  filter(
      name == "Germany" |
      name == "Spain" |
      name == "Italy" |
      name == "United Kingdom" |
      name == "France" 
  ) 
  
```
```{r fig.height=10, fig.width=20}
data %>% 
  filter(
      name == "South Korea" |
      name == "Iran" |
      name == "Germany" 
  ) %>% 
  filter(type=="historical") %>% 
  cases.timelime() 
```




```{r fig.height=15, fig.width=30}
data %>% 
  filter(
      name == "South Korea" |
      name == "Iran" |
      name == "Spain" |
      name == "Italy"  
  ) %>% 
  cases.timelime() 


```


```{r fig.height=10, fig.width=20}
data %>% 
  filter(type=="historical") %>% 
  group_by(name) %>% 
  arrange(cases) %>% 
  slice(n()) %>% 
  left_join(hospital.beds) %>% 
  left_join(population) %>% 
  mutate(cases.per.1M.inhabitants=cases/population.mio) %>% 
  select(name, beds.per.1M.inhabitants, cases.per.1M.inhabitants, cases) %>% 
  ggplot(aes(x=beds.per.1M.inhabitants, y=cases.per.1M.inhabitants)) +
  geom_point(aes(size=cases))+
  geom_label_repel(aes(label=name)) +
  scale_x_log10()+
  scale_y_log10(label=comma)+
  bbc_style()
```
```{r fig.height=10, fig.width=20}
data %>%
  filter(type == "historical") %>%
  group_by(name) %>%
  arrange(cases) %>%
  slice(n()) %>%
  left_join(hospital.beds) %>%
  left_join(population) %>%
  mutate(cases.per.1M.inhabitants = cases / population.mio) %>%
  mutate(risk = cases.per.1M.inhabitants / beds.per.1M.inhabitants) %>%
  select(name, risk) %>%
  na.omit() %>% 
  ggplot(aes(x = reorder(name, risk), risk)) +
  geom_bar(stat = "identity", fill="steelblue") +
  coord_flip() 
```

```{r}
data %>%
  filter(type == "historical") %>%
  group_by(name) %>%
  arrange(cases) %>%
  slice(n()) %>%
  left_join(hospital.beds) %>%
  left_join(population) %>% 
  filter(is.na(population.mio))
```

```{r}
hospital.beds %>% 
  mutate(name=ifelse(name=="Korea, Rep.", "South Korea", name), 
  name=ifelse(name=="Egypt, Arab Rep.", "Egypt", name),
  name=ifelse(name=="Iran, Islamic Rep.", "Iran", name),
  name=ifelse(name=="Russian Federation", "Russia", name))
```
```{r fig.height=10, fig.width=20}
data %>% 
  filter(
      name == "Germany" |
      name == "Spain" |
      name == "Italy" |
      name == "United Kingdom" |
      name == "France" 
  ) %>% 
  filter(type=="historical") %>% 
  cases.timelime() %>% german()
```

