---
title: "Google Mobilty"
author: "Jens Laufer"
date: "19 4 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(glue)
library(ggthemes)
source("dataGather.R")
source("dataPreprocess.R")
```

```{r}
mobility.data <- load.mobility.google() 
```




## Checking for missing values 



```{r}

mobility.data %>% 
  mutate(row=row_number()) %>% 
  gather(-row, key = "feature", value = "value") %>% 
  mutate(is_nan=is.na(value)) %>% 
  group_by(feature) %>% 
  mutate(total=n()) %>% 
  group_by(feature, is_nan, total) %>% 
  summarise(n=n()) %>%
  mutate(ratio=n/total, 
         ratio_pct=ifelse(is_nan==T, round(100*ratio,1), round(100*(1-ratio),1))) %>% 
  ungroup() %>%
  mutate(feature="{feature} ({ratio_pct}%)" %>% glue) %>% 
  select(-total, -n) %>% 
  ggplot(aes(x=feature, y=ratio, fill=is_nan)) +
  geom_bar(stat = "identity") +
  scale_fill_tableau() +
  coord_flip()

mobility.data <- mobility.data %>% select(-sub_region_2)
  
```



# Univariate Analysis



```{r fig.height=10, fig.width=20}
mobility.data %>% 
  select_if(is.numeric) %>% 
  gather(key = "feature", value = "value") %>% 
  ggplot(aes(x='', y=value)) +
  geom_boxplot() +
  coord_flip() +
  facet_wrap(~feature, scales = "free") 
```



## Multivariate Analysis

```{r}
mobility.data <- mobility.data  %>%
  mutate(
    timestamp = as.numeric(as.POSIXct(date)),
    overall_percent_change_from_baseline = (
      retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline
    ) / 6
  ) 
```




```{r fig.height=10, fig.width=20}
mobility.data %>%
  select(
    country_region,
    date,
    timestamp,
    overall_percent_change_from_baseline,
    sub_region_1
  ) %>%
  filter(!is.na(overall_percent_change_from_baseline) & is.na(sub_region_1)) %>%
  group_by(country_region) %>%
  nest() %>%
  mutate(mdl = map(
    data,
    ~ loess(overall_percent_change_from_baseline ~ timestamp, data = .)
  ),
  fit = map(mdl, `[[`, "fitted")) %>%
  ungroup() %>%
  select(-mdl) %>%
  unnest() %>%
  filter(
    
      country_region == "France" |
        country_region == "Germany" |
        country_region == "Spain" |
        country_region == "United Kingdom" |
        country_region == "Italy" |
        country_region == "United States"
    
    
  ) %>%
  ggplot(aes(x = date, y = fit, color =
               country_region)) +
  geom_line(aes(y = overall_percent_change_from_baseline)) +
  geom_line(size=2) +
  geom_hline(yintercept = 0) +
  scale_color_tableau() +
  scale_x_date(date_breaks = "2 day") +
  facet_wrap(~ country_region, scales = "free") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```



```{r}
confirmed <- load.data.bno.news() %>% 
  preprocess.data() %>% 
  filter(type=="historical") %>% 
  select(name, date, diff) %>% 
  rename(country_region=name) %>% 
  na.omit() %>% 
  filter(!is.infinite(diff))
```






```{r}
models <- confirmed %>%
  mutate(timestamp=as.numeric(as.POSIXct(date))) %>% 
  group_by(country_region) %>%
  nest() %>%
  mutate(mdl = map(data, ~ loess(diff ~ timestamp, data = .))) %>%
  mutate(fit = map(mdl, `[[`, "fitted")) %>% 
  ungroup()
```






```{r fig.height=10, fig.width=20}
models %>% 
  select(-mdl) %>% 
  unnest() %>% 
  filter(
      country_region == "France" |
        country_region == "Germany" |
        country_region == "Spain" |
        country_region == "United Kingdom" |
        country_region == "Italy" |
        country_region == "United States") %>% 
  group_by(country_region) %>% 
  ggplot(aes(x=date, y=fit, color=country_region)) +
  geom_line(size=2) + 
  geom_line(aes(y=diff)) +
  scale_color_tableau() +
  scale_x_date(date_breaks = "2 day") +
  facet_wrap( ~ country_region, scales="free") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



```{r}
filtered.confimed <- confirmed %>% 
  filter(
      country_region == "France" |
        country_region == "Germany" |
        country_region == "Spain" |
        country_region == "United Kingdom" |
        country_region == "Italy" |
        country_region == "United States") 
```

```{r}
filtered.mobility <- mobility.data %>% 
  filter(
      (country_region == "France" |
        country_region == "Germany" |
        country_region == "Spain" |
        country_region == "United Kingdom" |
        country_region == "Italy" |
        country_region == "United States") & is.na(sub_region_1)) %>% 
  select(country_region, date, overall_percent_change_from_baseline) 
```

```{r}
# filtered.confimed <- confirmed %>% 
#   filter(
#         country_region == "Germany" ) 
```

```{r}
# filtered.mobility <- mobility.data %>% 
#   filter(
#       (country_region == "Germany" ) & is.na(sub_region_1)) %>% 
#   select(country_region, date, overall_percent_change_from_baseline) 
```


```{r}
lag.data <- function(confirmed, mobility, .lag) {
  confirmed %>%
    inner_join(mobility) %>%
    mutate(lag=as.integer(.lag)) %>% 
    group_by(country_region) %>%
    mutate(overall_percent_change_from_baseline = lag(overall_percent_change_from_baseline, .lag)) %>%
    ungroup() %>%
    na.omit()
}

```


```{r}
diff.mobility.scatter.plot <- function(data) {
  data %>%
    ggplot(aes(x = overall_percent_change_from_baseline, y = diff)) +
    geom_point() +
    facet_wrap(~country_region)
}
```





```{r fig.height=10, fig.width=20}
seq(0,30,1) %>% 
  map(~lag.data(filtered.confimed, filtered.mobility, .)) %>% 
  bind_rows() %>% 
  group_by(country_region, lag) %>% 
  summarise(cor=cor(diff, overall_percent_change_from_baseline)) %>% 
  nest() %>%
  mutate(mdl = map(
    data,
    ~ loess(cor ~ lag, data = .)
  ),
  fit = map(mdl, `[[`, "fitted")) %>%
  select(-mdl) %>% 
  unnest() %>% 
  ggplot(aes(x=lag, y=cor, color=country_region)) +
  geom_line() +
  geom_line(aes(y=fit), size=2) +
  facet_wrap(~country_region)
```

seq(0,30,1) %>% 
  map(~lag.data(filtered.confimed, filtered.mobility, .)) %>% 
  bind_rows() %>% 
  group_by(country_region, lag) %>% 
  summarise(cor=cor(diff, overall_percent_change_from_baseline)) %>% 
  nest() %>%
  mutate(mdl = map(
    data,
    ~ loess(cor ~ lag, data = .)
  ),
  fit = map(mdl, `[[`, "fitted")) %>%
  select(-mdl) %>% 
  unnest()
```{r}
seq(0,30,1) %>% 
  map(~lag.data(filtered.confimed, filtered.mobility, .)) %>% 
  bind_rows() %>% 
  group_by(country_region, lag) %>% 
  summarise(cor=cor(diff, overall_percent_change_from_baseline)) %>% 
  nest() %>%
  mutate(mdl = map(
    data,
    ~ loess(cor ~ lag, data = .)
  ),
  fit = map(mdl, `[[`, "fitted")) %>%
  select(-mdl) %>% 
  unnest() %>%  
  ungroup() %>% 
  group_by(country_region) %>% 
  arrange(country_region, desc(fit)) %>% 
  slice(1:1)  %>% 
  group_by() %>% 
  summarise(mean=mean(lag), median=median(lag))
```

