---
title: "Google Mobilty"
author: "Jens Laufer"
date: "19.04.2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(glue)
library(ggthemes)
source("dataGather.R")
source("dataPreprocess.R")
source("visualisations.R")
```

```{r}
filtered.countries <- c("France", "Germany", "Spain", "United Kingdom", "Italy", "United States")
```


```{r}
mobility.data <- load.mobility.google(F) 
```


```{r}
confirmed <- load.data.bno.news() %>% 
  preprocess.data() %>% 
  filter(type=="historical") %>% 
  select(name, date, diff) %>% 
  rename(country_region=name) %>% 
  na.omit() %>% 
  filter(!is.infinite(diff))
```






## Checking for missing values 



```{r}
mobility.data %>% 
  mutate(row=row_number()) %>% 
  gather(-row, key = "feature", value = "value") %>% 
  mutate(is_nan=is.na(value)) %>% 
  group_by(feature) %>% 
  mutate(total=n()) %>% 
  group_by(feature, is_nan, total) %>% 
  summarise(n=n()) %>%
  mutate(ratio=n/total, 
         ratio_pct=ifelse(is_nan==T, round(100*ratio,1), round(100*(1-ratio),1))) %>% 
  ungroup() %>%
  mutate(feature="{feature} ({ratio_pct}%)" %>% glue) %>% 
  select(-total, -n) %>% 
  ggplot(aes(x=feature, y=ratio, fill=is_nan)) +
  geom_bar(stat = "identity") +
  scale_fill_tableau() +
  coord_flip()

```




# Univariate Analysis



```{r fig.height=10, fig.width=20}
mobility.data %>% 
  select_if(is.numeric) %>% 
  gather(key = "feature", value = "value") %>% 
  ggplot(aes(x='', y=value)) +
  geom_boxplot() +
  coord_flip() +
  facet_wrap(~feature, scales = "free") 
```



## Multivariate Analysis

```{r}
mobility.data <- preprocess.mobility.data(mobility.data)
```


```{r fig.height=10, fig.width=20}
cases.model.data %>%
  filter(country_region %in% filtered.countries) %>%
  group_by(country_region) %>%
  plot.model.data(.feature1 = "date", .feature2 = "diff")
```


```{r  fig.height=10, fig.width=20}
feature <- "overall_percent_change_from_baseline"
(
  mobility.data %>%
    group_by(country_region, sub_region_1) %>%
    fit.loess.model(feature, "timestamp")
)$data %>%
  filter(!is.na(!!sym(feature)) &
           is.na(sub_region_1)) %>%
  filter(country_region %in% filtered.countries) %>%
  plot.model.data(.feature1 = "date", .feature2 = feature)
```






I filter all countries with significant decrease in mobility:

```{r}
mobility.chg <- mobility.data %>% 
  filter(is.na(sub_region_1) & !is.na(overall_percent_change_from_baseline)) %>% 
  select(country_region, date, overall_percent_change_from_baseline) %>% 
  arrange(country_region, -overall_percent_change_from_baseline) %>% 
  group_by(country_region) %>% 
  slice(1:1,n():n()) %>% 
  mutate(chg=overall_percent_change_from_baseline-lag(overall_percent_change_from_baseline)) %>% 
  na.omit() %>% 
  select(country_region, chg) %>% 
  arrange(chg) %>% 
  filter(chg < -70)
  
mobility.chg
```



```{r}
seq(0,30,1) %>% 
  map(~lag.data(confirmed %>% inner_join(mobility.chg), mobility.data %>% inner_join(mobility.chg), ., "overall_percent_change_from_baseline")) %>% 
  bind_rows() %>% 
  group_by(country_region, lag) %>% 
  summarise(cor=cor(diff, overall_percent_change_from_baseline)) %>% 
  ungroup() %>% 
  group_by(country_region) %>% 
  arrange(country_region, -cor) %>% 
  slice(1:1)  %>% 
  ungroup() %>% 
  ggplot(aes(x="", y=lag)) +
  geom_boxplot() +
  geom_jitter(alpha=0.3)
```




```{r fig.height=10, fig.width=20}
feature <- "transit_stations_percent_change_from_baseline"
(
  mobility.data %>%
    group_by(country_region, sub_region_1) %>%
    fit.loess.model(feature, "timestamp")
)$data %>%
  mutate(date = date + 14) %>%
  filter(!is.na(overall_percent_change_from_baseline) &
           is.na(sub_region_1)) %>%
  filter(country_region %in% filtered.countries) %>%
  plot.model.data(.feature1 = "date", .feature2 = feature)
```


```{r  fig.height=10, fig.width=20}
feature <- "parks_percent_change_from_baseline_diff"

(
  mobility.data %>% filter(!is.na(!!sym(feature)) &
                             !is.infinite(!!sym(feature))) %>%
    group_by(country_region, sub_region_1) %>% fit.loess.model(feature, "timestamp")
)$data %>%
  mutate(date = date + 14) %>%
  filter(!is.na(overall_percent_change_from_baseline) &
           is.na(sub_region_1)) %>%
  #mutate(!!feature:=-!!sym(feature), fit=-fit) %>%
  filter(country_region %in% filtered.countries) %>%
  plot.model.data(.feature1 = "date",
                  .feature2 = feature,
                  .show.noise = T)
```



