---
title: "corr2"
author: "Jens Laufer"
date: "28 4 2020"
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ggthemes)
library(lubridate)
library(forecast)

source("dataGather.R")
source("dataPreprocess.R")
source("visualisations.R")
```


```{r}
mobility.data <- load.mobility.google(T) %>% 
  preprocess.mobility.data() %>% 
  filter(is.na(sub_region_1)) %>% 
  select(-sub_region_1, -country_region_code)
```


```{r}
cases.data <- load.data.bno.news() %>% 
  preprocess.data() %>% 
  filter(type=="historical") %>% 
  select(name, date, diff) %>% 
  rename(country_region=name) %>% 
  na.omit() %>% 
  filter(!is.infinite(diff)) 
```


```{r fig.height=10, fig.width=20}
countries <- c("France", "Germany", "Spain", "United Kingdom", "Italy", "United States", 
                        "Sweden", "Austria", "Switzerland", "Belgium", "Netherlands", 
               "Canada", "Slovakia", "Norway", "Poland", "South Korea")
.lag <- 20

calc.corr <- function(cases.data, mobility.data, .lag) {
  cases.data %>%
    inner_join(mobility.data) %>%
    select(-timestamp) %>%
    select_if(!str_detect(colnames(.), "_diff")) %>%
    gather(-country_region,
           -date,
           -diff,
           key = "feature",
           value = "value") %>%
    group_by(country_region, feature) %>%
    mutate(value = lag(value, .lag)) %>%
    na.omit() %>%
    ungroup() %>%
    group_by(feature) %>%
    summarise(cor = cor(diff, value), lag = .lag) 
}



(seq(0, 30, 1) %>%
  map( ~ calc.corr(
    cases.data %>% filter(country_region %in% countries),
    mobility.data,
    .
  )) %>%
  bind_rows() %>% 
  group_by(feature) %>% 
  fit.loess.model("cor", "lag", "feature"))$data  %>% 
  ggplot() +
  geom_line(aes(x=lag, y=cor, color=feature)) +
  geom_line(aes(x=lag, y=fit, color=feature), size=2) +
  scale_color_tableau() +
  facet_wrap(~feature, scales="free")


```
 %>% 
  ggplot(aes(x=lag, y=cor)) +
  geom_line() +
  facet_wrap(~feature, scales = "free")

models <- data %>%
      filter(!is.na(!!sym(.feature1))) %>%
      mutate(num = n()) %>%
      filter(num > 1) %>%
      select(-num) %>%
      nest() %>%
      mutate(mdl = map(data,
                       ~ loess(
                         !!sym(.feature1) ~ !!sym(.feature2), data = .
                       )),
             fit = map(mdl, `[[`, "fitted")) %>%
      ungroup()
    
    list(
      "data" = models %>% select(-mdl) %>% unnest(),
      "models" = models %>% select(!!sym(.id), mdl)
    )