---
title: "Google Mobilty"
author: "Jens Laufer"
date: "19 4 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(glue)
library(ggthemes)
source("dataGather.R")
source("dataPreprocess.R")
source("visualisations.R")
```

```{r}
filtered.countries <- c("France", "Germany", "Spain", "United Kingdom", "Italy", "United States", 
                        "Sweden", "Austria", "Switzerland", "Belgium", "Netherlands", "Canada")
```


```{r}
mobility.data <- load.mobility.google(T) %>% preprocess.mobility.data()
```


```{r}
confirmed <- load.data.bno.news() %>% 
  preprocess.data() %>% 
  filter(type=="historical") %>% 
  select(name, date, diff) %>% 
  rename(country_region=name) %>% 
  na.omit() %>% 
  filter(!is.infinite(diff))
```







```{r}
cases.model.data <-  (confirmed %>% mutate(timestamp=as.numeric(as.POSIXct(date))) %>% 
  group_by(country_region) %>% fit.loess.model("diff", "timestamp"))$data


filtered.confirmed <- cases.model.data %>%
  filter(country_region %in% filtered.countries)

filtered.mobility <- mobility.data %>% 
  filter(country_region %in% filtered.countries) %>% 
  filter(is.na(sub_region_1)) %>% 
  select(-sub_region_1) 
```


```{r fig.height=10, fig.width=20}
plot.mobility.type.cases.diff.plot <-
  function(cases, mobility, feature, group = "country_region", plot.group="country_region") {
    (
      seq(0, 30, 1) %>%
        map( ~ lag.data(cases,
                        mobility,
                        .,
                        feature,
                        .group = group)) %>%
        bind_rows() %>%
        group_by(!!sym(group), lag) %>%
        summarise(cor = cor(diff, !!sym(feature))) %>%
        na.omit() %>%
        fit.loess.model("cor", "lag", group)
    )$data %>%
      mutate(!!feature := feature) %>%
      plot.model.data(
        .feature1 = "lag",
        .feature2 = "cor",
        is.date = F,
        .groupvar = plot.group
      ) +
      ggtitle(label = feature)
  }

```

```{r}

```


```{r fig.height=10, fig.width=20}
filtered.mobility %>% 
  select_if(str_detect(names(.), "percent_change_from_baseline") & !str_detect(names(.), "_diff")) %>%  
  colnames() %>%  
  map(~plot.mobility.type.cases.diff.plot(filtered.confirmed, filtered.mobility, ., group = "", plot.group = (.)))
  
```


```{r fig.height=10, fig.width=20}
filtered.mobility %>% 
  select_if(str_detect(names(.), "percent_change_from_baseline") & !str_detect(names(.), "_diff")) %>%  
  colnames() %>%  
  map(~plot.mobility.type.cases.diff.plot(filtered.confirmed, filtered.mobility, .))
  
```







```{r}
merged <- filtered.mobility.normalized %>%  inner_join(filtered.confirmed, by=c("country_region"="country_region", "date"="date"))
```

```{r fig.height=10, fig.width=20}
library(ggrepel)
source("visualisations.R")
filtered.mobility %>%
  select_if(str_detect(names(.), "percent_change_from_baseline") &
              !str_detect(names(.), "_diff")) %>%
  colnames() %>%  
  map(~ (diff.mobility.scatter.plot(merged, .)))

```











