---
title: "Prediction Coronvirus"
author: "Jens Laufer"
date: "2020/02/01"
output:
  md_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(bbplot)
library(scales)
library(forecast)
library(tsbox)
library(lubridate)
```


```{r}
confirmed <- read_csv("data/Confirmed.csv") 
death <- read_csv("data/Death.csv")
recovered <-  read_csv("data/Recovered.csv")
```



```{r}
confirmed <-
  confirmed %>% gather(
    -`Province/State`,
    -`Country/Region`,
    -`First confirmed date in country`,
    -Lat,
    -Long,
    key = "date",
    value = "confirmed"
  ) %>%
  mutate(
    confirmed = replace_na(confirmed, 0),
    `Province/State` = as.factor(`Province/State`),
    `Country/Region` = as.factor(`Country/Region`),
    `First confirmed date in country` = as.Date(`First confirmed date in country`, format =
                                                         "%m/%d/%Y"),
    datetime = as.POSIXct(date),
    date = as.Date(datetime)
  ) %>%
  group_by(`Province/State`, `Country/Region`, date) %>%
  top_n(1) %>%
  arrange(`Country/Region`, `Province/State`, datetime) %>%
  group_by(`Country/Region`, `Province/State`) %>%
  mutate(confirmed_chg_pct = confirmed / dplyr::lag(confirmed)) %>%
  ungroup()
```


```{r}
death <-
  death %>% gather(
    -`Province/State`,
    -`Country/Region`,
    -`First confirmed date in country`,
    -Lat,
    -Long,
    key = "date",
    value = "death"
  ) %>%
  mutate(
    death = replace_na(death, 0),
    `Province/State` = as.factor(`Province/State`),
    `Country/Region` = as.factor(`Country/Region`),
    `First confirmed date in country` = as.Date(`First confirmed date in country`, format =
                                                         "%m/%d/%Y"),
    datetime = as.POSIXct(date),
    date = as.Date(datetime)
  ) %>%
  group_by(`Province/State`, `Country/Region`, date) %>%
  top_n(1) %>%
  arrange(`Country/Region`, `Province/State`, datetime) %>%
  group_by(`Country/Region`, `Province/State`) %>%
  mutate(death_chg_pct = death / dplyr::lag(death)) %>%
  ungroup()
```

```{r}
recovered <-
  recovered %>% gather(
    -`Province/State`,
    -`Country/Region`,
    -`First confirmed date in country`,
    -Lat,
    -Long,
    key = "date",
    value = "recovered"
  ) %>%
  mutate(
    recovered = replace_na(recovered, 0),
    `Province/State` = as.factor(`Province/State`),
    `Country/Region` = as.factor(`Country/Region`),
    `First confirmed date in country` = as.Date(`First confirmed date in country`, format =
                                                         "%m/%d/%Y"),
    datetime = as.POSIXct(date),
    date = as.Date(datetime)
  ) %>%
  group_by(`Province/State`, `Country/Region`, date) %>%
  top_n(1) %>%
  arrange(`Country/Region`,`Country/Region`,  datetime) %>%
  group_by(`Country/Region`, `Province/State`) %>%
  mutate(recovered_chg_pct = recovered / dplyr::lag(recovered)) %>%
  ungroup()
```

```{r}
data <- confirmed %>% 
  left_join(death %>% select(-Lat, -Long, -`First confirmed date in country`,-date)) %>% 
  left_join(recovered %>% select(-Lat, -Long, -`First confirmed date in country`,-date))

rm(confirmed)
rm(death)
rm(recovered)
```



```{r fig.height=10, fig.width=20}
data %>% group_by(datetime) %>% 
  summarise(total=sum(confirmed)) %>% 
  ungroup() %>% 
  ggplot(aes(x=datetime, y=total)) +
  #geom_line()+
  geom_smooth() +
  bbc_style()
```


```{r fig.height=10, fig.width=20}
ts_c(data %>% group_by(datetime) %>% 
  summarise(total=sum(confirmed)) %>% 
  ungroup() %>% select(total)) %>% 
auto.arima() %>%
  forecast(h = 10) %>% 
  autoplot() +
  scale_y_continuous(labels = comma) +
  bbc_style()
```

```{r fig.height=20, fig.width=20}
data %>% 
  group_by(`Country/Region`, datetime) %>%
  summarise(total=sum(confirmed)) %>% 
  ungroup() %>% 
  ggplot(aes(x=datetime, y=total)) +
  geom_line()+
  geom_point(size=2)+
  facet_wrap(~`Country/Region`, scales = "free_y")+
  bbc_style()
  
```
```{r fig.height=20, fig.width=20}

data %>% 
  filter(`Country/Region` == "Mainland China") %>% 
  group_by(`Province/State`, datetime) %>%
  summarise(total=sum(confirmed)) %>% 
  ungroup() %>% 
  ggplot(aes(x=datetime, y=total)) +
  geom_line()+
  geom_point(size=2)+
  facet_wrap(~`Province/State`, scales = "free_y")+
  bbc_style()
  
```




```{r fig.height=20, fig.width=20}
data %>% 
  filter(`Country/Region` == "Mainland China") %>% 
  ggplot(aes(x=date, y=confirmed_chg_pct))+
  geom_bar(stat="identity") +
  geom_smooth()+
  facet_wrap(~`Province/State`) +
  bbc_style()
  
```

```{r}
mainland.china <- data %>%
  group_by(`Country/Region`, date) %>%
  summarise(
    confirmed = sum(confirmed),
    death = sum(death),
    recovered = sum(recovered)
  ) %>%
  mutate(
    confirmed_chg_pct = confirmed / dplyr::lag(confirmed),
    death_chg_pct = death / dplyr::lag(death),
    recovered_chg_pct = recovered / dplyr::lag(recovered),
    death_rate=death/confirmed,
    recovery_rate=death/recovered,
  ) %>%
  ungroup() %>% 
  filter(`Country/Region` == "Mainland China")
```




```{r}
mainland.china %>% 
  ggplot(aes(x=date, confirmed_chg_pct)) +
  geom_bar(stat="identity") +
  geom_smooth()
```


